import React from 'react';
import img1 from './title1/science5.webp';
import background from './sciback2.jpeg';

const Sciblog5 = () => {
  return (
    <div style={styles.wrapper}>
      <div style={styles.container}>
        {/* Title */}
        <h1 style={styles.title}>Science Blogs</h1>

        {/* Description */}
        <div style={styles.description}>
          <h2 style={styles.subtitle}>Challenging the Norm: New Solar Cell Model Surpasses 80-Year-Old Equation
          </h2>
        </div>

        {/* Metadata (Date and Author) */}
        <div style={styles.metadata}>
          <span style={styles.date}> July 30, 2024</span>
          <span style={styles.author}> |  Swansea University </span>
        </div>

        {/* First Paragraph */}
        <p style={styles.paragraph}>
          <b>Researchers have developed a new analytical model that enhances the understanding and efficiency of thin-film photovoltaic (PV) devices, challenging the longstanding Shockley diode equation. Their findings illuminate how these flexible, low-cost solar cells can achieve higher efficiency by balancing electricity collection and minimizing charge recombination losses.

</b>
        </p>

        {/* First Image */}
        <div style={styles.imageWrapper}>
          <img
            src={img1}
            alt="Science Illustration"
            style={styles.img1}
          />
          <p style={styles.caption}>Figure 1: A new model from Swansea and Åbo Akademi universities improves thin-film solar cell efficiency. It addresses the limitations of the traditional Shockley diode equation, optimizing electricity collection and minimizing recombination losses.

</p>
        </div>

        {/* Second Paragraph */}
        <p style={styles.paragraph}>
        
        Physicists at Swansea University and Åbo Akademi University have achieved a major advancement in solar cell technology by creating a new analytical model. This model enhances the understanding and efficiency of thin-film photovoltaic (PV) devices.<br></br><br></br>

For nearly eight decades, the so-called Shockley diode equation has explained how current flows through solar cells; the electrical current that powers up your home or charges the battery bank. However, the new study challenges this traditional understanding of a specific class of next-generation solar cells, namely: thin-film solar cells.<br></br><br></br>

These thin-film solar cells, made of flexible, low-cost materials have had limited efficiency due to factors that the existing analytical models couldn’t fully explain.<br></br><br></br>

The new study sheds light on how these solar cells achieve optimal efficiency. It reveals a critical balance between collecting the electricity generated by light and minimizing losses due to recombination, where electrical charges cancel each other out.<br></br><br></br>

“Our findings provide key insights into the mechanisms driving and limiting charge collection, and ultimately the power-conversion efficiency, in low-mobility PV devices,” said the lead author, Dr. Oskar Sandberg of Åbo Akademi University, Finland.<br></br>
<h2>New Model Captures the Missing Piece</h2>
Previous analytical models for these solar cells had a blind spot: “injected carriers” — charges entering the device from the contacts. These carriers significantly impact recombination and limited efficiency.<br></br><br></br>

“The traditional models just weren’t capturing the whole picture, especially for these thin-film cells with low-mobility semiconductors,” explained the principal investigator, Associate Professor Ardalan Armin of Swansea University. “Our new study addresses this gap by introducing a new diode equation specifically tailored to account for these crucial injected carriers and their recombination with those photogenerated.”<br></br><br></br>

“The recombination between injected charges and photogenerated ones is not a huge problem in traditional solar cells such as silicon PV which is hundreds of times thicker than next-generation thin film PV such as organic solar cells,” Dr. Sandberg added.<br></br><br></br>
Associate Professor Armin said: “One of the brightest theoretical physicists of all times, Wolfgang Pauli once said ‘God made the bulk; the surface was the work of the devil’. As thin film solar cells have much bigger interfacial regions per bulk than traditional silicon; no wonder why they get affected more drastically by “the work of the devil” – that is recombination of precious photogenerated charges with injected ones near the interface!”
<h2>Impact on Future Solar Cell Development</h2>
This new model offers a new framework for designing more efficient thin solar cells and photodetectors, optimizing existing devices, and analyzing material properties. It can also aid in training machines used for device optimisation marking a significant step forward in the development of next-generation thin-film solar cells.
        </p> 
      </div>
    </div>
  );
};

const styles = {
  wrapper: {
    backgroundImage: `url(${background})`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    minHeight: '100vh',
    padding: '20px',
  },
  container: {
    padding: '30px',
    fontFamily: "'Merriweather', serif",
    lineHeight: '1.8',
    color: '#333',
    maxWidth: '900px',
    margin: '0 auto',
    backgroundColor: 'rgba(255, 255, 255, 0.9)', // Adds a slight white overlay to improve text readability
    boxShadow: '0px 0px 20px rgba(0, 0, 0, 0.1)',
    borderRadius: '10px',
  },
  title: {
    fontSize: '3rem',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: '20px',
    color: '#2c3e50',
    textShadow: '2px 2px 4px rgba(0, 0, 0, 0.1)',
  },
  subtitle: {
    fontSize: '1.5rem',
    fontWeight: 'normal',
    marginBottom: '10px',
    color: '#34495e',
  },
  description: {
    fontSize: '1.2rem',
    margin: '0 auto',
    width: '80%',
    textAlign: 'center',
    marginBottom: '10px',
    color: '#666',
  },
  metadata: {
    textAlign: 'center',
    fontSize: '0.9rem',
    color: '#999',
    marginBottom: '20px',
  },
  date: {
    marginRight: '10px',
  },
  author: {
    marginLeft: '10px',
  },
  paragraph: {
    fontSize: '1.1rem',
    marginBottom: '25px',
    color: '#4a4a4a',
    textAlign: 'justify',
  },
  subheading: {
    fontSize: '1.3rem',
    fontWeight: 'bold',
    marginTop: '20px',
    color: '#34495e',
  },
  imageWrapper: {
    textAlign: 'center',
    marginBottom: '25px',
  },
  img1: {
    width: '100%',
    height: 'auto',
    borderRadius: '10px',
    boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.1)',
  },

  caption: {
    fontSize: '0.9rem',
    color: '#7f8c8d',
    marginTop: '10px',
  },
};

export default Sciblog5;
